name: Build TWRP Recovery for Yunluo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true

    - name: Initialize Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagej lib32ncurses-dev lib32z1-dev libelf-dev libgl1-mesa-dev libxml2-utils xsltproc zip libssl-dev python3 python-is-python3

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Sync TWRP Source
      run: |
        mkdir twrp_12.1 && cd twrp_12.1
        git config --global user.name "Builder"
        git config --global user.email "builder@github.com"
        git config --global color.ui false
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1
        repo sync -c -j4 --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree
      run: |
        cd twrp_12.1
        git clone https://github.com/xiaomi-mt6789-devs/android_device_xiaomi_yunluo device/xiaomi/yunluo

    - name: Compile TWRP
      run: |
        cd twrp_12.1
        source build/envsetup.sh
        lunch twrp_yunluo-eng
        mka recoveryimage -j$(nproc --all)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Yunluo
        path: |
          twrp_12.1/out/target/product/yunluo/recovery.img
          twrp_12.1/out/target/product/yunluo/vendor_boot.img
